### ISSUE TITLE
Unable to build colibri-t20 image

### ISSUE THREAD

**Issue by ubx** [maluethi/meta-glide#7]
Build command:
`MACHINE="colibri-t20" bitbake console-tdx-image`
....
....
NOTE: Resolving any missing task queue dependencies
ERROR: Nothing RPROVIDES 'tdx-oak-sensorsxcsoar-7.0' (but /home/yocto/oe-core/build/../layers/meta-toradex-demos/recipes-images/images/console-tdx-image.bb RDEPENDS on or otherwise requires it)
NOTE: Runtime target 'tdx-oak-sensorsxcsoar-7.0' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['tdx-oak-sensorsxcsoar-7.0']
ERROR: Required build target 'console-tdx-image' has no buildable providers.
Missing or unbuildable dependency chain was: ['console-tdx-image', 'tdx-oak-sensorsxcsoar-7.0']

**Comment by maluethi** [comment]
https://github.com/maluethi/meta-glide/commit/824e55f89280a8554a2aefed98e8e21ceecba4f9 fixes this. But now cannot get python3-urwid'

NOTE: Resolving any missing task queue dependencies
ERROR: Nothing RPROVIDES 'python3-urwid' (but /home/yocto/oe-core/build/../layers/meta-toradex-demos/recipes-images/images/console-tdx-image.bb RDEPENDS on or otherwise requires it)

NOTE: Runtime target 'python3-urwid' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['python3-urwid']
ERROR: Required build target 'console-tdx-image' has no buildable providers.
Missing or unbuildable dependency chain was: ['console-tdx-image', 'python3-urwid']

**Comment by maluethi** [comment]
https://github.com/maluethi/meta-glide/commit/b96eb389a7cdef28cab887c0fc207f46a24b444d removing the python libraries, the build is succesful.
